# Generated by Django 5.2.7 on 2025-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_description_alter_habit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='tag',
            field=models.CharField(choices=[('health', 'Health'), ('learning', 'Learning'), ('work', 'Work'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
