# Generated by Django 5.2.7 on 2025-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_tag_habitlog_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='habit',
            name='tag',
        ),
        migrations.AddField(
            model_name='habit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='habits.tag'),
        ),
    ]
