# Generated by Django 5.2.7 on 2025-12-06 12:37

from django.db import migrations

def create_default_tags(apps, schema_editor):
    Tag = apps.get_model('habits', 'Tag')
    default_tags = ['Health', 'Work', 'Personal', 'Learning', 'Fitness', 'Finance']
    for tag_name in default_tags:
        Tag.objects.create(name=tag_name)

class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_tag_remove_habit_tag_habit_tags'),
    ]

    operations = [
        migrations.RunPython(create_default_tags),
    ]
