# Generated by Django 5.2.7 on 2025-12-09 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_seed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
